"""创建 share_files 与 shortcodes 表

Revision ID: 119278987572
Revises: b1d0aa031613
Create Date: 2026-08-13 14:26:26.325255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119278987572'
down_revision: Union[str, Sequence[str], None] = 'b1d0aa031613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('preview_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('download_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_files_code'), 'share_files', ['code'], unique=True)
    op.create_table('shortcodes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_shortcodes_kind'), 'shortcodes', ['kind'], unique=False)
    # ### end Alembic commands ###

    # 手工回填：存量文本分享的短码登记进短码中心表（kind='share'），
    # 保证既有短码在「跨类型全局唯一」约束下继续有效，创建新资源不受影响
    op.execute(
        "INSERT INTO shortcodes (code, kind, created_at) "
        "SELECT code, 'share', created_at FROM shares"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortcodes_kind'), table_name='shortcodes')
    op.drop_table('shortcodes')
    op.drop_index(op.f('ix_share_files_code'), table_name='share_files')
    op.drop_table('share_files')
    # ### end Alembic commands ###
