"""加固 share_files 与 shortcodes 约束

Revision ID: 2afe9b4d1b32
Revises: 119278987572
Create Date: 2026-08-13 14:36:21.914568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afe9b4d1b32'
down_revision: Union[str, Sequence[str], None] = '119278987572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'share_files', ['stored_name'])
    op.create_check_constraint('ck_shortcodes_kind', 'shortcodes', "kind IN ('share', 'file')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_shortcodes_kind', 'shortcodes', type_='check')
    op.drop_constraint(None, 'share_files', type_='unique')
    # ### end Alembic commands ###
