<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ClipShare.Windows.Infrastructure</RootNamespace>
    <AssemblyName>ClipShare.Windows.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ClipShare.Windows.Application/ClipShare.Windows.Application.csproj" />
    <ProjectReference Include="../ClipShare.Windows.Vault/ClipShare.Windows.Vault.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
